[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.cursor]
cursor = "#e06c75"
text = "0xffffff"

[colors.dim]
black = "0x333333"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xdddddd"
yellow = "0xffcc66"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xffffff"
yellow = "0xe6c547"

[colors.primary]
#background = "0x000000"
#foreground = "0xffffff"
background = "#1a1b26"
foreground = "#a9b1d6"

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true


[font]
normal.family = "CommitMono Nerd Font"
bold.family = "CommitMono Nerd Font"
italic.family = "CommitMono Nerd Font"
bold_italic.family = "CommitMono Nerd Font"

size = 14.0

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

# [terminal.shell]
# args = ["-NoLogo"]
# program = "pwsh.exe"

[terminal.shell]
program = "nu"

[window]
opacity = 0.65

padding.x = 0
padding.y = 0

decorations = "None"

# decorations = "Full"
# title = "Az~Alacritty"
# dynamic_title = false

decorations_theme_variant = "Dark"

[window.dimensions]
columns = 135
lines = 40

[keyboard]
bindings = [
  { key = "q", mods = "Alt", action = "Quit" },
  { key = "v", mods = "Alt", action = "ToggleViMode" },
  { key = "v", mods = "Control", action = "Paste" },
]
